const $ = id => document.getElementById(id);
const state = {view:'all',person:'',personName:'',folder:'',items:[],total:0,selected:0,drive:{},library:null,request:0,semanticResult:null,embeddings:null};
const escapeHtml = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes = n => {if(!n)return '0 B';let i=Math.min(3,Math.floor(Math.log(n)/Math.log(1024)));return `${(n/1024**i).toFixed(i?1:0)} ${['B','KB','MB','GB'][i]}`};
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6500)}
async function api(path,payload){const response=await fetch(path,payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data}
const safely = fn => async(...args)=>{try{await fn(...args)}catch(error){toast(error.message);const dialog=document.querySelector('dialog[open]:last-of-type')||Array.from(document.querySelectorAll('dialog[open]')).pop();if(dialog){let status=dialog.querySelector('.actionError');if(!status){status=document.createElement('p');status.className='actionError';status.setAttribute('role','alert');dialog.append(status)}status.textContent=error.message;}}};
function folderName(folder){return folder.path.startsWith('gdrive:')?folder.path.split(':').slice(2).join(':'):folder.path.split(/[\\/]/).filter(Boolean).pop()}
async function library(){const [lib,drive]=await Promise.all([api('/api/library'),api('/api/drive')]);state.library=lib;state.drive=drive;$('statTotal').textContent=lib.stats.total.toLocaleString();$('navCount').textContent=lib.stats.total;$('statSize').textContent=bytes(lib.stats.bytes);$('statFolders').textContent=lib.folders.length;$('statDuplicates').textContent=lib.stats.duplicates;$('connectionState').textContent=drive.connected?'Connected · Read-only access':'Not connected';$('connect').textContent=drive.connected?'Reconnect Google Drive':'Connect Google Drive';$('mobileFolder').innerHTML='<option value="">All folders</option>'+lib.folders.map(folder=>`<option value="${folder.id}">${escapeHtml(folderName(folder))} (${folder.count})</option>`).join('');$('mobileFolder').value=state.folder;$('folders').replaceChildren();for(const folder of lib.folders){const button=document.createElement('button');button.className='folder'+(String(folder.id)===state.folder?' selected':'');button.title=folder.path;button.textContent='▱ '+folderName(folder);const count=document.createElement('small');count.textContent=folder.count;button.append(count);button.onclick=safely(async()=>{state.folder=String(folder.id);state.view='all';await refresh()});$('folders').append(button)}const chosen=$('format').value;$('format').innerHTML='<option value="">All formats</option>'+lib.formats.map(f=>`<option value="${escapeHtml(f)}">${escapeHtml(f.toUpperCase())}</option>`).join('');$('format').value=chosen;$('emptyAction').textContent=drive.connected?'Add Drive folder':'Connect Google Drive';}
function render(){const gallery=$('gallery');gallery.replaceChildren();state.items.forEach((item,index)=>{const card=document.createElement('button');card.className='card';card.setAttribute('aria-label','Open '+item.name);card.innerHTML=`<div class="picture"><img loading="lazy" decoding="async" src="/thumb/${item.id}" alt="${escapeHtml(item.name)}">${item.favorite?'<span class="heart">♥</span>':''}</div><div class="cardinfo"><strong>${escapeHtml(item.name)}</strong><p><span>${item.width&&item.height?item.width+' × '+item.height:item.extension.toUpperCase()}</span><span>${bytes(item.size)}</span>${typeof item.score==='number'?`<span class="similarity" title="Cosine similarity, not a probability">Similarity ${item.score.toFixed(3)}</span>`:''}</p></div>`;card.querySelector('img').onerror=event=>{event.target.remove();const fallback=document.createElement('span');fallback.textContent='Preview unavailable';card.querySelector('.picture').prepend(fallback)};card.onclick=()=>photoClick(index);gallery.append(card);decorateSelection(card,item)});$('headingCount').textContent=state.total.toLocaleString();$('results').textContent=`${state.total.toLocaleString()} image${state.total===1?'':'s'}${state.items.length<state.total?' · '+state.items.length+' shown':''}`;$('more').hidden=state.items.length>=state.total;$('empty').hidden=state.items.length>0;const filtered=state.library?.stats.total>0;$('emptyTitle').textContent=filtered?'No images here yet.':'A home for every image.';$('emptyText').textContent=filtered?'Try another search, filter, or folder.':'Connect Google Drive, then add an image folder. Browse your collection here without moving a thing.';$('emptyAction').hidden=filtered;if(state.semanticResult){$('results').textContent=`${state.total.toLocaleString()} images ranked by visual similarity${state.semanticResult.unindexed?' · '+state.semanticResult.unindexed+' not indexed yet':''}`;if(!state.total&&state.semanticResult.unindexed){$('emptyTitle').textContent='Image embeddings are not ready.';$('emptyText').textContent='Use Index images above. You can search names and tags while indexing runs.';$('emptyAction').hidden=true}}}
async function images(append=false){
  if(state.view==='people'){++state.request;return renderPeople(append);}
  const request=++state.request;
  const semantic=$('searchMode').value==='semantic'&&!!$('search').value.trim();
  $('sort').disabled=semantic;
  $('sort').title=semantic?'Visual results are ordered by similarity':'';
  $('results').textContent=semantic?'Searching image content…':'Loading images…';
  const query=new URLSearchParams({q:$('search').value,mode:$('searchMode').value,sort:$('sort').value,format:$('format').value,view:state.view,folder:state.folder,person:state.person,offset:append?state.items.length:0});
  try{
    const result=await api('/api/images?'+query);if(request!==state.request)return;
    state.semanticResult=result.semantic?result:null;
    state.items=append?[...state.items,...result.items]:result.items;state.total=result.total;render();
  }catch(error){
    if(request!==state.request)return;
    state.items=[];state.total=0;state.semanticResult=null;render();
    $('results').textContent='Search failed';$('emptyTitle').textContent='Search unavailable';$('emptyText').textContent=error.message;$('emptyAction').hidden=true;throw error;
  }
}
async function refresh(){await library();setPeopleLayout();const folder=state.library.folders.find(f=>String(f.id)===state.folder);const title=folder?folderName(folder):({all:'All images',favorites:'Favorites',duplicates:'Duplicates',people:'People',review:'Faces without labels'}[state.view]);$('title').firstChild.textContent=state.person?state.personName:title;$('crumb').textContent=title;$('subtitle').textContent=state.view==='duplicates'?'Identical files, grouped by their content checksum.':'A little more order. A lot more room to explore.';document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===state.view&&!state.folder));await images()}
function addFolder(){$('folderDialog').showModal();$('folderPath').focus()}
async function connect(){if(!['127.0.0.1','localhost'].includes(location.hostname)){toast('Connect Google Drive on the PC running Imadex first. Then browse here from your phone.');return}state.drive=await api('/api/drive');if(!state.drive.configured){$('setupDialog').showModal();return}const result=await api('/api/drive/connect',{});window.location.assign(result.url)}
function view(index){state.selected=index;const item=state.items[index];if(!item)return;$('viewerName').textContent=item.name;$('detailName').textContent=item.name;$('fullImage').src='/thumb/'+item.id;$('loadFull').disabled=false;$('loadFull').textContent='Load full-resolution image';$('previewStatus').textContent='Loading preview…';$('fullImage').alt=item.name;$('favorite').textContent=item.favorite?'♥ Favorited':'♡ Add to favorites';$('tags').value=item.tags;$('metadata').innerHTML=[['Dimensions',item.width+' × '+item.height],['Format',item.extension.toUpperCase()],['File size',bytes(item.size)],['Modified',new Date(item.mtime*1000).toLocaleString()],['Camera',item.camera||'—'],['Taken',item.taken||'—']].map(([k,v])=>`<dt>${k}</dt><dd>${escapeHtml(v)}</dd>`).join('');$('openOriginal').href=item.drive_id?'https://drive.google.com/file/d/'+encodeURIComponent(item.drive_id)+'/view':'/image/'+item.id;$('openOriginal').textContent=item.drive_id?'Open in Google Drive ↗':'Open original ↗';$('previous').disabled=index===0;$('next').disabled=index===state.items.length-1;if(!$('viewer').open)$('viewer').showModal();safely(loadPhotoPeople)(item)}
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>$(button.dataset.close).close());document.querySelectorAll('[data-view]').forEach(button=>button.onclick=safely(async()=>{state.view=button.dataset.view;state.folder='';if(['people','all'].includes(state.view))state.person='';await refresh()}));['addFolder','addSmall','addTop'].forEach(id=>$(id).onclick=addFolder);$('connect').onclick=safely(connect);$('retryConnect').onclick=safely(connect);$('emptyAction').onclick=safely(()=>state.drive.connected?addFolder():connect());$('source').onchange=()=>{$('folderPath').placeholder=$('source').value==='drive'?'https://drive.google.com/drive/folders/…':'C:\\Users\\You\\Pictures'};
$('folderForm').onsubmit=safely(async event=>{event.preventDefault();$('saveFolder').disabled=true;try{const result=await api('/api/folders',{path:$('folderPath').value,source:$('source').value});$('folderDialog').close();$('folderPath').value='';state.folder=String(result.id);state.view='all';await refresh();await api('/api/scan',{folder_id:result.id});wasRunning=true;await poll()}finally{$('saveFolder').disabled=false}});
$('rescan').onclick=safely(async()=>{const folder=state.folder||state.library.folders[0]?.id;if(!folder)return addFolder();if(!state.folder&&state.library.folders.length>1){toast('Select a folder in the sidebar to scan it.');return}await api('/api/scan',{folder_id:Number(folder)});wasRunning=true;await poll()});let debounce;$('search').oninput=()=>{clearTimeout(debounce);debounce=setTimeout(safely(()=>images()),650)};['sort','format'].forEach(id=>$(id).onchange=safely(()=>images()));$('more').onclick=safely(async()=>{$('more').disabled=true;try{await images(true)}finally{$('more').disabled=false}});$('previous').onclick=()=>view(state.selected-1);$('next').onclick=()=>view(state.selected+1);$('favorite').onclick=safely(async()=>{const item=state.items[state.selected];await api('/api/image',{id:item.id,favorite:!item.favorite});item.favorite=!item.favorite;view(state.selected);render();await library()});$('saveTags').onclick=safely(async()=>{const item=state.items[state.selected];await api('/api/image',{id:item.id,tags:$('tags').value});item.tags=$('tags').value;toast('Tags saved')});$('viewer').addEventListener('close',safely(()=>images()));document.addEventListener('keydown',event=>{if(['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName))return;if(event.key==='/'&&!document.querySelector('dialog[open]')){event.preventDefault();$('search').focus()}if($('viewer').open){if(event.key==='ArrowLeft'&&state.selected>0)view(state.selected-1);if(event.key==='ArrowRight'&&state.selected<state.items.length-1)view(state.selected+1)}});
let wasRunning=false,wasEmbedding=false;
async function poll(){
 const [status,embedding]=await Promise.all([api('/api/status'),api('/api/embeddings')]);
 $('scanStatus').textContent=status.message;$('rescan').disabled=status.running;
 $('scanErrors').hidden=!status.errors.length;$('scanErrors').textContent=status.errors.join('\n');
 state.embeddings=embedding;
 $('embeddingStatus').textContent=`${embedding.ready} / ${embedding.total} images ready${embedding.failed?' · '+embedding.failed+' failed':''}`;
 $('embeddingProgress').max=Math.max(1,embedding.total);$('embeddingProgress').value=embedding.ready;
 $('embeddingMessage').textContent=embedding.running?embedding.message:(embedding.error||'Describe a scene, object, or color. Embeddings stay on this PC.');
 $('indexEmbeddings').disabled=embedding.running;$('indexEmbeddings').textContent=embedding.running?'Indexing…':(embedding.failed||embedding.error?'Retry indexing':'Index images');
 const errors=[...(embedding.error?[embedding.error]:[]),...embedding.errors];
 $('embeddingErrors').hidden=!errors.length;$('embeddingErrors').textContent=errors.join('\n');
 if((wasRunning&&!status.running)||(wasEmbedding&&!embedding.running))await refresh();
 wasRunning=status.running;wasEmbedding=embedding.running;
}
$('searchMode').onchange=safely(async()=>{$('search').placeholder=$('searchMode').value==='semantic'?'Describe an image, e.g. a beach at sunset…':'Search names, tags, or camera…';await images()});
$('indexEmbeddings').onclick=safely(async()=>{await api('/api/embeddings',{});wasEmbedding=true;clearTimeout(pollTimer);pollTimer=setTimeout(scheduledPoll,200);toast('Image indexing queued. You can keep browsing.');});


$('mobileFolder').onchange=safely(async()=>{state.folder=$('mobileFolder').value;state.view='all';await refresh()});
$('fullImage').onload=()=>{$('previewStatus').textContent=''};
$('fullImage').onerror=()=>{$('previewStatus').textContent='Preview unavailable. Try the full image or open the original.'};
$('loadFull').onclick=()=>{const item=state.items[state.selected];if(!item)return;$('fullImage').src='/image/'+item.id;$('previewStatus').textContent='Loading full image…';$('loadFull').disabled=true;$('loadFull').textContent='Full-resolution image selected'};
let touchStart=null;
const canvas=document.querySelector('.imagecanvas');
canvas.addEventListener('touchstart',event=>{touchStart=event.touches.length===1?{x:event.touches[0].clientX,y:event.touches[0].clientY,time:Date.now()}:null},{passive:true});
canvas.addEventListener('touchmove',event=>{if(event.touches.length>1)touchStart=null},{passive:true});
canvas.addEventListener('touchcancel',()=>{touchStart=null},{passive:true});
canvas.addEventListener('touchend',event=>{if(!touchStart||!event.changedTouches.length)return;const touch=event.changedTouches[0],dx=touch.clientX-touchStart.x,dy=touch.clientY-touchStart.y;const quick=Date.now()-touchStart.time<650;touchStart=null;if(!quick||Math.abs(dx)<65||Math.abs(dx)<Math.abs(dy)*2)return;if(dx<0&&state.selected<state.items.length-1)view(state.selected+1);else if(dx>0&&state.selected>0)view(state.selected-1)},{passive:true});
let pollTimer, pollBusy=false;
async function scheduledPoll(){clearTimeout(pollTimer);if(pollBusy)return;pollBusy=true;try{if(!document.hidden)await poll()}catch{$('scanStatus').textContent='Connection lost. Retrying…'}finally{pollBusy=false;pollTimer=setTimeout(scheduledPoll,(wasRunning||wasEmbedding)?2000:15000)}}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)scheduledPoll()});
window.addEventListener('DOMContentLoaded',()=>{safely(refresh)();scheduledPoll()});


$('toggleStats').onclick=()=>{const expanded=$('toggleStats').getAttribute('aria-expanded')!=='true';$('toggleStats').setAttribute('aria-expanded',String(expanded));$('libraryStats').classList.toggle('expanded',expanded);$('toggleStats').textContent=expanded?'Hide library overview ⌃':'Library overview ⌄'};
